enum GLOBAL_KEYS {
  SHOULD_SHOW_LOADING = 'SHOULD_SHOW_LOADING',
}
const GLOBAL_VALUES = {
  [GLOBAL_KEYS.SHOULD_SHOW_LOADING]: false,
}
enum ENTITY_NAME {
  'GLOBAL' = 'global',
}
export { GLOBAL_KEYS, GLOBAL_VALUES, ENTITY_NAME }
